services:
  geolocator:
    image: ${DOCKER_REGISTRY-}geolocator
    build:
      context: .
      dockerfile: Geolocator/Dockerfile
    env_file:
      - geolocator.env
    ports:
     - "3001:8081"
     - "3000:8080" 
    depends_on:
     - postgres15
     - elasticsearch
    networks:
     - geolocator-network

  postgres15:
    image: postgres:15
    container_name: postgres15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geolocator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - geolocator-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx3g"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - index.codec=best_compression
      - indices.fielddata.cache.size=20%
      - thread_pool.write.size=4
      - indices.memory.index_buffer_size=30%
      - thread_pool.write.queue_size=100
      - thread_pool.search.queue_size=200
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - geolocator-network

volumes:
 postgres_data:
 elasticsearch_data:
 
networks:
  geolocator-network:
    driver: bridge